COMPONENT=BlinkToRadioAppC
# CFLAGS += -I$(TOSDIR)/lib/printf -I$(TOSDIR)/chips/rf2xx/rf230 -I$(TOSDIR)/platforms/inga/chips/rf230 -I$(TOSDIR)/chips/rf2xx/layers -I$(TOSDIR)/chips/rf2xx/util -DPACKET_LINK
CFLAGS += -I$(TOSDIR)/lib/printf -DRADIO_DEBUG
include $(MAKERULES)

